CREATE TABLE IF NOT EXISTS sessions (
    id VARCHAR(36) DEFAULT (UUID()) PRIMARY KEY NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,

    token VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    user_id VARCHAR(36) NOT NULL
);