CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(36) DEFAULT (UUID()) PRIMARY KEY NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,

    email VARCHAR(255),
    password VARCHAR(255),
    password_salt VARCHAR(255),

    UNIQUE (email)
);