CREATE TABLE IF NOT EXISTS room_mods (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,

    user_id VARCHAR(36) NOT NULL,
    room_id VARCHAR(36) NOT NULL,
    role TINYINT NOT NULL -- 0 = Owner (all perms), 1 = Moderator (Most perms)
);