CREATE TABLE IF NOT EXISTS room_users (
    id VARCHAR(36) DEFAULT (UUID()) PRIMARY KEY NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,

    room_id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULl,
    muted BOOL DEFAULT FALSE NOT NULL
);